package com.sarwoedhi.albumapps.utils

object Params {
    const val EXTRA_KEY_MOVIE = "EXTRA_KEY_MOVIE"
    const val BUNDLE_TITLE_DIALOG = "BUNDLE_TITLE_DIALOG"
    const val BUNDLE_DESC_DIALOG = "BUNDLE_DESC_DIALOG"
    const val BUNDLE_BUTTON_DIALOG = "BUNDLE_BUTTON_DIALOG"
    const val BUNDLE_ICON_DIALOG = "BUNDLE_ICON_DIALOG"
    const val BUNDLE_DETAIL_DATA_DIALOG = "BUNDLE_DETAIL_DATA_DIALOG"
}